export type AppLocale = 'ar' | 'en' | 'he'

export const locales: AppLocale[] = ['ar', 'en', 'he']

export const messages = {
  ar: {
    localeName: 'العربية', languageArabic: 'العربية', languageEnglish: 'English', languageHebrew: 'עברית', direction: 'rtl', brand: 'دليل', university: 'جامعة الخليل', advisor: 'المرشد الأكاديمي',
    closeSidebar: 'إخفاء القائمة', openSidebar: 'إظهار القائمة', mobileMenu: 'فتح القائمة', newChat: 'محادثة جديدة', history: 'المحادثات السابقة', noHistory: 'ستظهر محادثاتك هنا', deleteConversation: 'حذف المحادثة', confirmDeleteConversation: 'هل تريد حذف هذه المحادثة نهائياً؟', conversationDeleteError: 'تعذر حذف المحادثة. حاول مجدداً.', attachmentCleanupError: 'حُذفت المحادثة، لكن تعذر حذف أحد مرفقاتها.',
    copyright: 'جميع الحقوق محفوظة © 2026', designedBy: 'مصمم بواسطة', showPassword: 'إظهار كلمة المرور', hidePassword: 'إخفاء كلمة المرور',
    dailyMessages: 'رسائلك اليوم', renewLimit: 'يتجدد الحد يومياً عند منتصف الليل', welcomeKicker: 'مرشدك الأكاديمي في جامعة الخليل', greeting: 'أهلاً بك', greetingBack: 'أهلاً بعودتك يا', welcomeQuestion: 'كيف أقدر أساعدك؟', welcomeCopy: 'اسأل عن خطتك الدراسية، معدلك، أو الساعات المتبقية. سنساعدك على ترتيب خطواتك الأكاديمية بوضوح.',
    suggestions: ['كيف أحسب معدلي التراكمي؟', 'ساعدني في فهم خطتي الدراسية', 'كم ساعة متبقية لي للتخرج؟', 'ما الفرق بين المعدل الفصلي والتراكمي؟'],
    composerPlaceholder: 'اكتب سؤالك الأكاديمي هنا...', attach: 'إرفاق صور أو ملفات', voice: 'الإملاء الصوتي', stopVoice: 'إيقاف الإملاء الصوتي', send: 'إرسال الرسالة', shortcut: 'Enter للإرسال · Shift + Enter لسطر جديد', privacyHint: 'احرص على عدم مشاركة معلوماتك الشخصية أو كلمة المرور داخل المحادثة.',
    account: 'إعدادات الحساب', accountTitle: 'حسابك الشخصي', guestTitle: 'مرحباً بك في دليل', accountDescription: 'حدّث اسمك أو سجّل الخروج من حسابك.', guestDescription: 'احفظ محادثاتك وسجّل الدخول من أي جهاز.', displayName: 'اسم العرض', namePlaceholder: 'اسمك الذي نرحب بك به', saveAccount: 'حفظ معلومات الحساب', signOut: 'تسجيل الخروج', signIn: 'تسجيل الدخول', signUp: 'إنشاء حساب', switchToSignup: 'ليس لديك حساب؟ أنشئ حساباً جديداً', switchToSignin: 'لديك حساب؟ سجّل الدخول', orSignIn: 'أو سجّل الدخول', email: 'البريد الإلكتروني', password: 'كلمة المرور', confirmPassword: 'تأكيد كلمة المرور', passwordPlaceholder: '6 أحرف على الأقل', nameRequired: 'اكتب اسمك الكامل.', passwordMismatch: 'كلمتا المرور غير متطابقتين.',
    settings: 'الإعدادات', settingsTitle: 'إعدادات الموقع', language: 'لغة الموقع', theme: 'لون الواجهة', themeGreen: 'أخضر', themeOcean: 'بحري', themeRose: 'مرجاني', themeGold: 'ذهبي', saveSettings: 'تم حفظ التفضيلات',
    cookieTitle: 'أهلاً بك في دليل', cookieDescription: 'اختر اسماً للترحيب بك، وحدد تفضيلات ملفات الارتباط. التخزين الضروري للمحادثات يعمل حتى عند رفض الاختياري.', cookieName: 'الاسم الذي نستخدمه للترحيب', acceptAll: 'قبول الكل', rejectAll: 'رفض الكل',
    thinking: 'أراجع سؤالك الأكاديمي...', outOfScope: 'عذراً، ليس من صلاحياتي المساعدة في هذا الموضوع. أستطيع مساعدتك في الإرشاد الأكاديمي لجامعة الخليل.',
    loading: 'جارٍ تحميل محادثاتك...', guestSaved: 'حُفظت المحادثة على هذا الجهاز وستُحذف بعد 24 ساعة من آخر نشاط.', signInForFiles: 'سجّل الدخول أولاً لرفع ملفاتك إلى مساحة خاصة وآمنة.',
    micUnsupported: 'الإملاء الصوتي غير مدعوم في هذا المتصفح. جرّب Chrome أو Safari.', micPermission: 'تعذر التقاط الصوت. تحقق من صلاحية الميكروفون وحاول مجدداً.',
    databaseLoadError: 'تعذر تحميل سجل المحادثات. تحقق من إعداد قاعدة البيانات.', fileTooLarge: 'الحد الأقصى لحجم الملف الواحد هو 10 ميجابايت.', unsupportedFile: 'نوع الملف غير مدعوم: {name}', tooManyFiles: 'يمكن إرفاق {count} ملفات كحد أقصى في الرسالة.', uploadFailed: 'فشل رفع أحد الملفات. أعد المحاولة وتأكد من إعداد Storage.',
    dailyLimitReached: 'وصلت إلى الحد اليومي: 40 رسالة. يتجدد الحد عند منتصف الليل.', quotaExhausted: 'استهلكت رسائلك الأربعين لهذا اليوم. حاول مجدداً غداً.', conversationLoadError: 'تعذر فتح هذه المحادثة.', messageSaveError: 'تعذر حفظ الرسالة. تحقق من إعداد قاعدة البيانات.', messageSavedGuest: 'حُفظت المحادثة على هذا الجهاز وستُحذف بعد 24 ساعة من آخر نشاط.', advisorUnavailable: 'حُفظ سؤالك، لكن تعذر الحصول على رد من المرشد. حاول لاحقاً.',
    nameSaveRequired: 'اكتب الاسم الذي تود أن نرحب بك به.', nameSaveError: 'تعذر تحديث الاسم في حسابك.', profileSaved: 'تم تحديث معلومات الحساب.', supabaseConfigRequired: 'إعدادات Supabase مطلوبة لتفعيل الحسابات.', emailConfirmation: 'تم إنشاء الحساب. راجع بريدك الإلكتروني لتأكيده، ثم سجّل الدخول.', signupSuccess: 'تم إنشاء الحساب بنجاح.', loginSuccess: 'أهلاً بعودتك.', signedOut: 'تم تسجيل الخروج.', filePicker: 'اختيار صور أو ملفات', attachedFiles: 'الملفات المرفقة', openAttachment: 'فتح الملف {name}', profile: 'الملف الشخصي',
    close: 'إغلاق', fileRemove: 'إزالة الملف', dailyLimitLabel: 'حد الاستخدام اليومي', guestUpgrade: 'اربط حساباً لحفظ محادثاتك بعد انتهاء جلسة الضيف.', accountLinked: 'تم ربط الحساب. تحقق من بريدك لتأكيده.', messageTooLong: 'الحد الأقصى لطول الرسالة 8000 حرف.', guestAuthError: 'تعذر بدء جلسة الضيف. تأكد من تفعيل تسجيل الدخول المجهول في Supabase، أو سجّل الدخول بالبريد.', guestSignInWarning: 'تسجيل الدخول إلى حساب موجود ينقل الجلسة، وقد تبقى محادثات الضيف حتى انتهاء مدتها.',
  },
  en: {
    localeName: 'English', languageArabic: 'العربية', languageEnglish: 'English', languageHebrew: 'עברית', direction: 'ltr', brand: 'Daleel', university: 'Hebron University', advisor: 'Academic Advisor',
    closeSidebar: 'Hide sidebar', openSidebar: 'Show sidebar', mobileMenu: 'Open menu', newChat: 'New chat', history: 'Recent chats', noHistory: 'Your chats will appear here', deleteConversation: 'Delete conversation', confirmDeleteConversation: 'Delete this conversation permanently?', conversationDeleteError: 'Could not delete this conversation. Try again.', attachmentCleanupError: 'The conversation was deleted, but one of its attachments could not be removed.',
    copyright: '© 2026 All rights reserved', designedBy: 'Designed by', showPassword: 'Show password', hidePassword: 'Hide password',
    dailyMessages: 'Messages today', renewLimit: 'Daily limit resets at midnight', welcomeKicker: 'Your Hebron University academic advisor', greeting: 'Welcome', greetingBack: 'Welcome back,', welcomeQuestion: 'How can I help?', welcomeCopy: 'Ask about your study plan, GPA, or remaining credit hours. We will help you map your next academic steps.',
    suggestions: ['How do I calculate my cumulative GPA?', 'Help me understand my study plan', 'How many credits do I need to graduate?', 'What is the difference between semester and cumulative GPA?'],
    composerPlaceholder: 'Ask an academic question...', attach: 'Attach images or files', voice: 'Voice dictation', stopVoice: 'Stop voice dictation', send: 'Send message', shortcut: 'Enter to send · Shift + Enter for a new line', privacyHint: 'Avoid sharing passwords or sensitive personal information in chat.',
    account: 'Account settings', accountTitle: 'Your account', guestTitle: 'Welcome to Daleel', accountDescription: 'Update your name or sign out.', guestDescription: 'Save your chats and access them from any device.', displayName: 'Display name', namePlaceholder: 'Name to greet you by', saveAccount: 'Save account details', signOut: 'Sign out', signIn: 'Sign in', signUp: 'Create account', switchToSignup: 'New here? Create an account', switchToSignin: 'Already registered? Sign in', orSignIn: 'Or sign in', email: 'Email address', password: 'Password', confirmPassword: 'Confirm password', passwordPlaceholder: 'At least 6 characters', nameRequired: 'Enter your full name.', passwordMismatch: 'Passwords do not match.',
    settings: 'Settings', settingsTitle: 'App settings', language: 'Language', theme: 'Accent color', themeGreen: 'Green', themeOcean: 'Ocean', themeRose: 'Coral', themeGold: 'Gold', saveSettings: 'Preferences saved',
    cookieTitle: 'Welcome to Daleel', cookieDescription: 'Choose a name for your greeting and set cookie preferences. Essential storage for chats remains active if optional cookies are rejected.', cookieName: 'Name for your greeting', acceptAll: 'Accept all', rejectAll: 'Reject all',
    thinking: 'Reviewing your academic question...', outOfScope: 'Sorry, I can’t help with that topic. I can help with academic advising for Hebron University.',
    loading: 'Loading your chats...', guestSaved: 'Saved on this device. Guest chats expire 24 hours after the last activity.', signInForFiles: 'Sign in to upload files to your private storage.',
    micUnsupported: 'Voice dictation is not supported here. Try Chrome or Safari.', micPermission: 'Microphone access failed. Check permission and try again.',
    databaseLoadError: 'Could not load your chat history. Check your database setup.', fileTooLarge: 'Each file must be 10 MB or smaller.', unsupportedFile: 'Unsupported file type: {name}', tooManyFiles: 'You can attach up to {count} files per message.', uploadFailed: 'A file could not be uploaded. Check your Supabase Storage setup and try again.',
    dailyLimitReached: 'You reached the daily limit of 40 messages. It resets at midnight.', quotaExhausted: 'You have used all 40 messages for today. Try again tomorrow.', conversationLoadError: 'Could not open this conversation.', messageSaveError: 'Could not save the message. Check your database setup.', messageSavedGuest: 'Saved on this device. Guest chats expire 24 hours after the last activity.', advisorUnavailable: 'Your question was saved, but the advisor could not reply. Try again later.',
    nameSaveRequired: 'Enter the name you want us to use.', nameSaveError: 'Could not update your account name.', profileSaved: 'Account details updated.', supabaseConfigRequired: 'Supabase settings are required to enable accounts.', emailConfirmation: 'Account created. Check your email to confirm it, then sign in.', signupSuccess: 'Account created successfully.', loginSuccess: 'Welcome back.', signedOut: 'Signed out.', filePicker: 'Choose images or files', attachedFiles: 'Attached files', openAttachment: 'Open file {name}', profile: 'Profile',
    close: 'Close', fileRemove: 'Remove file', dailyLimitLabel: 'Daily usage limit', guestUpgrade: 'Link an account to keep your chats after the guest session expires.', accountLinked: 'Account linked. Check your email to confirm it.', messageTooLong: 'Messages are limited to 8,000 characters.', guestAuthError: 'Could not start a guest session. Enable anonymous sign-ins in Supabase, or sign in with email.', guestSignInWarning: 'Signing into an existing account switches identities; guest chats remain until their expiry.',
  },
  he: {
    localeName: 'עברית', languageArabic: 'العربية', languageEnglish: 'English', languageHebrew: 'עברית', direction: 'rtl', brand: 'دليل', university: 'אוניברסיטת חברון', advisor: 'יועץ אקדמי',
    closeSidebar: 'הסתרת סרגל צד', openSidebar: 'הצגת סרגל צד', mobileMenu: 'פתיחת תפריט', newChat: 'שיחה חדשה', history: 'שיחות אחרונות', noHistory: 'השיחות שלך יופיעו כאן', deleteConversation: 'מחיקת שיחה', confirmDeleteConversation: 'למחוק את השיחה לצמיתות?', conversationDeleteError: 'לא ניתן למחוק את השיחה. נסו שוב.', attachmentCleanupError: 'השיחה נמחקה, אך לא ניתן היה למחוק אחד מהקבצים המצורפים.',
    copyright: '© 2026 כל הזכויות שמורות', designedBy: 'עוצב על ידי', showPassword: 'הצגת הסיסמה', hidePassword: 'הסתרת הסיסמה',
    dailyMessages: 'הודעות היום', renewLimit: 'המגבלה מתאפסת בחצות', welcomeKicker: 'היועץ האקדמי שלך באוניברסיטת חברון', greeting: 'שלום', greetingBack: 'טוב שחזרת,', welcomeQuestion: 'איך אפשר לעזור?', welcomeCopy: 'אפשר לשאול על תוכנית הלימודים, הממוצע או נקודות הזכות שנותרו. נעזור לך לתכנן את הצעדים האקדמיים הבאים.',
    suggestions: ['איך מחשבים ממוצע מצטבר?', 'עזור לי להבין את תוכנית הלימודים', 'כמה נקודות זכות נותרו לי לתואר?', 'מה ההבדל בין ממוצע סמסטריאלי למצטבר?'],
    composerPlaceholder: 'כתבו כאן שאלה אקדמית...', attach: 'צירוף תמונות או קבצים', voice: 'הכתבה קולית', stopVoice: 'עצירת ההכתבה', send: 'שליחת הודעה', shortcut: 'Enter לשליחה · Shift + Enter לשורה חדשה', privacyHint: 'אין לשתף סיסמאות או מידע אישי רגיש בשיחה.',
    account: 'הגדרות חשבון', accountTitle: 'החשבון שלך', guestTitle: 'ברוכים הבאים לייעוץ האקדמי', accountDescription: 'עדכון השם או יציאה מהחשבון.', guestDescription: 'שמרו את השיחות וגשו אליהן מכל מכשיר.', displayName: 'שם לתצוגה', namePlaceholder: 'השם שבו נפנה אליך', saveAccount: 'שמירת פרטי חשבון', signOut: 'יציאה', signIn: 'כניסה', signUp: 'יצירת חשבון', switchToSignup: 'חדש כאן? יצירת חשבון', switchToSignin: 'כבר רשומים? כניסה', orSignIn: 'או כניסה', email: 'כתובת אימייל', password: 'סיסמה', confirmPassword: 'אימות סיסמה', passwordPlaceholder: 'לפחות 6 תווים', nameRequired: 'נא להזין שם מלא.', passwordMismatch: 'הסיסמאות אינן תואמות.',
    settings: 'הגדרות', settingsTitle: 'הגדרות האתר', language: 'שפת האתר', theme: 'צבע הממשק', themeGreen: 'ירוק', themeOcean: 'ים', themeRose: 'אלמוג', themeGold: 'זהב', saveSettings: 'ההעדפות נשמרו',
    cookieTitle: 'ברוכים הבאים לייעוץ האקדמי', cookieDescription: 'בחרו שם לברכה והגדירו העדפות עוגיות. אחסון חיוני לשיחות יפעל גם אם תדחו עוגיות אופציונליות.', cookieName: 'השם לברכה', acceptAll: 'אישור הכול', rejectAll: 'דחיית הכול',
    thinking: 'בודק את השאלה האקדמית...', outOfScope: 'מצטערים, איני מוסמך לסייע בנושא זה. ניתן לשאול אותי על ייעוץ אקדמי באוניברסיטת חברון.',
    loading: 'טוען את השיחות...', guestSaved: 'השיחה נשמרה במכשיר ותימחק 24 שעות לאחר הפעילות האחרונה.', signInForFiles: 'יש להתחבר כדי להעלות קבצים לאחסון הפרטי.',
    micUnsupported: 'הכתבה קולית אינה נתמכת בדפדפן זה. נסו Chrome או Safari.', micPermission: 'לא ניתן לגשת למיקרופון. בדקו את ההרשאה ונסו שוב.',
    databaseLoadError: 'לא ניתן לטעון את היסטוריית השיחות. בדקו את הגדרות מסד הנתונים.', fileTooLarge: 'גודל כל קובץ חייב להיות עד 10 מגה-בייט.', unsupportedFile: 'סוג קובץ לא נתמך: {name}', tooManyFiles: 'אפשר לצרף עד {count} קבצים להודעה.', uploadFailed: 'העלאת קובץ נכשלה. בדקו את הגדרות Supabase Storage ונסו שוב.',
    dailyLimitReached: 'הגעתם למגבלה היומית של 40 הודעות. היא מתאפסת בחצות.', quotaExhausted: 'נוצלו כל 40 ההודעות להיום. נסו שוב מחר.', conversationLoadError: 'לא ניתן לפתוח את השיחה.', messageSaveError: 'לא ניתן לשמור את ההודעה. בדקו את הגדרות מסד הנתונים.', messageSavedGuest: 'נשמר במכשיר. שיחות אורח יימחקו 24 שעות לאחר הפעילות האחרונה.', advisorUnavailable: 'השאלה נשמרה, אך היועץ לא הצליח להשיב. נסו שוב מאוחר יותר.',
    nameSaveRequired: 'נא להזין את השם שבו נשתמש.', nameSaveError: 'לא ניתן לעדכן את שם החשבון.', profileSaved: 'פרטי החשבון עודכנו.', supabaseConfigRequired: 'נדרשות הגדרות Supabase להפעלת החשבונות.', emailConfirmation: 'החשבון נוצר. בדקו את האימייל לאישור ולאחר מכן התחברו.', signupSuccess: 'החשבון נוצר בהצלחה.', loginSuccess: 'טוב שחזרת.', signedOut: 'יצאתם מהחשבון.', filePicker: 'בחירת תמונות או קבצים', attachedFiles: 'קבצים מצורפים', openAttachment: 'פתיחת הקובץ {name}', profile: 'פרופיל',
    close: 'סגירה', fileRemove: 'הסרת קובץ', dailyLimitLabel: 'מגבלת שימוש יומית', guestUpgrade: 'קשרו חשבון כדי לשמור שיחות לאחר סיום מפגש האורח.', accountLinked: 'החשבון קושר. בדקו את האימייל לאישור.', messageTooLong: 'אורך ההודעה מוגבל ל־8,000 תווים.', guestAuthError: 'לא ניתן להתחיל מפגש אורח. הפעילו כניסת משתמשים אנונימיים ב־Supabase, או התחברו באימייל.', guestSignInWarning: 'כניסה לחשבון קיים מחליפה זהות; שיחות האורח יישארו עד לתפוגתן.',
  },
} as const

export function detectLocale(): AppLocale {
  const cookieLocale = document.cookie.split('; ').find((cookie) => cookie.startsWith('daleel_locale='))?.split('=')[1]
  if (cookieLocale === 'ar' || cookieLocale === 'en' || cookieLocale === 'he') return cookieLocale

  const browserLanguages = navigator.languages?.length ? navigator.languages : [navigator.language]
  for (const language of browserLanguages) {
    const normalized = language.toLowerCase()
    if (normalized.startsWith('ar')) return 'ar'
    if (normalized.startsWith('he') || normalized.startsWith('iw')) return 'he'
    if (normalized.startsWith('en')) return 'en'
  }
  return 'en'
}